version: '3.8'

services:
  minecraft:
    image: daweedpanic/papermc
    container_name: pmc
    stdin_open: true
    tty: true
    stop_grace_period: 1m # Wait this long for server shutdown
    restart: always
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8123:8123'
    volumes:
      - '/home/min/src/levisiteur/server:/server/'
